# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitopsctl" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "2547058b6489a53df82a107ca380b9060d9cc6ac0979293d08565ca47ad0871e"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5eb366ed462380f3ad08083e11b910d6657bd39bae944e5c50e4bef5b66bb145"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f196af7eb0d5c72e8ca1174d64f09ecf962ed22a1c01ec1250a15027c5304e8"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "44c868f88bcaa32fc740d5a1f7f14b3d69a075c205d23ef7d59335cecb75b621"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Linux_arm64.tar.gz"
    end
  end

  name "gitopsctl"
  desc "A minimalistic, self-hosted, and externally managed GitOps controller."
  homepage "https://github.com/aeswibon/gitopsctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitopsctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitopsctl"]
    end
  end

  # No zap stanza required

end
