# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitopsctl" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "52fb7c804a326cc4f2119c41800eda6f47358a05de63b5a5e717555b9029db11"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b3c41452a3c138030e81ca7b727636a0e9bea52c1f4c5ec99b99c15c950f49f7"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "844fe7c3daed95514b562404fcfa74e6b632a95ce1d37885a378b833d59a4a9c"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bfeb3e7def527eac5bd8ae57ab25c39f581b9a7e33fd40a8244893af20e057b"
      url "https://github.com/aeswibon/gitopsctl/releases/download/v#{version}/gitopsctl_Linux_arm64.tar.gz"
    end
  end

  name "gitopsctl"
  desc "A minimalistic, self-hosted, and externally managed GitOps controller."
  homepage "https://github.com/aeswibon/gitopsctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitopsctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitopsctl"]
    end
  end

  # No zap stanza required

end
